### ISSUE TITLE
Dont start

### ISSUE THREAD

**Issue by zumorra** [dfgHiatus/NoVRCFT#1]
![Sin título](https://user-images.githubusercontent.com/71853798/168113008-1fd7329e-1fc0-4130-a512-1caf1fd4a4d4.png)
![Sin título2](https://user-images.githubusercontent.com/71853798/168113249-6991bc3f-25c5-4ced-85b4-e3f26de658a2.png)
i start all but no osc output

**Comment by dfgHiatus** [comment]
Hey there! So I can recreate this, can you answer the following questions:

- Is your avatar setup for VRCFT? What avatar/parameters are you using?
- Do you have OSC enabled? A screenshot of this would be helpful
- Does changing the input stream type do anything? I know for some people YUY2 works but MJPEG doesn't, and vice versa

Finally, I see you have the websocket-sharp file in your CustomLibs folder - this doesn't need to be there, it needs to be in the same folder as VRCFT.exe.

**Comment by zumorra** [comment]
1- yes l have
2- yes and also open the debug for see if something happend
3- i try both

**Comment by dfgHiatus** [comment]
Closed due to inactivity
