### ISSUE TITLE
VRCFaceTracking Not Working

### ISSUE THREAD

**Issue by molresa** [dfgHiatus/NoVRCFT#2]
Hello, I did have normally setup anything like the installation said but, getting a lot of errors in the VRCFaceTracking console and it's too don't work.
![image](https://user-images.githubusercontent.com/26688240/189288124-728d8cc6-fce5-4e14-896c-767583815e9a.png)

**Comment by dfgHiatus** [comment]
Thanks for the heads-up! I'll look into this, I have a feeling it's a locale-related parsing issue

**Comment by dfgHiatus** [comment]
Made a new build, try this out: https://github.com/dfgHiatus/NoVRCFT/releases/tag/v1.0.1a

All you need to do is replace `WCFace.dll` with this one

**Comment by molresa** [comment]
Did try right now with the file you did send (Did replace it only in the CustomLibs folder) And now when I do want to launch VRCFaceTracking, it's just crash with this error (Hope it's okay that some part of the error are in French since it's my main language): 
![image](https://user-images.githubusercontent.com/26688240/189449315-9da56d0d-7787-4038-aa79-fa31feaa3a2b.png)

**Comment by dfgHiatus** [comment]
Could you copy that text into a file? I think I have an idea of what's going on

**Comment by molresa** [comment]
Here the text :

[00:17:21] VRCFT Standalone Initializing!
[00:17:21] Loaded library C:\Users\Hugo\AppData\Roaming\VRCFaceTracking\StockLibs\libHTC_License.dll
[00:17:21] Loaded library C:\Users\Hugo\AppData\Roaming\VRCFaceTracking\StockLibs\nanomsg.dll
[00:17:21] Loaded library C:\Users\Hugo\AppData\Roaming\VRCFaceTracking\StockLibs\SRWorks_Log.dll
[00:17:21] Loaded library C:\Users\Hugo\AppData\Roaming\VRCFaceTracking\StockLibs\ViveSR_Client.dll
[00:17:21] Loaded library C:\Users\Hugo\AppData\Roaming\VRCFaceTracking\StockLibs\SRanipal.dll
[00:17:21] Loaded library C:\Users\Hugo\AppData\Roaming\VRCFaceTracking\StockLibs\PimaxEyeTracker.dll
[00:17:21] Initialized DependencyManager Successfully
[00:17:21] Initialized UnifiedLibManager Successfully
[00:17:21] Finding and initializing runtimes...
[00:17:21] Loading External Modules...
[00:17:21] Loading C:\Users\Hugo\AppData\Roaming\VRCFaceTracking\CustomLibs\WCFace.dll
[00:17:21] [WARNING] Due to a bug with VRChat's current OSC implementation, it's important you pause the runtime before switching avatars, and unpause when the swap has completed.
Press P to toggle the pause state.

Exception non gérée : System.IO.FileLoadException: Impossible de charger le fichier ou l'assembly 'file:///C:\Users\Hugo\AppData\Roaming\VRCFaceTracking\CustomLibs\WCFace.dll' ou une de ses dépendances. L'opération n'est pas prise en charge. (Exception de HRESULT : 0x80131515) ---> System.NotSupportedException: Tentative de chargement d'un assembly à partir d'un emplacement réseau qui aurait entraîné l'utilisation de l'assembly en mode Bac à sable (sandbox) dans les versions antérieures du .NET Framework. Cette version du .NET Framework n'activant pas la stratégie CAS par défaut, ce chargement peut être dangereux. Si ce chargement n'est pas destiné à utiliser l'assembly en mode Bac à sable (sandbox), activez le commutateur loadFromRemoteSources. Pour plus d'informations, consultez http://go.microsoft.com/fwlink/?LinkId=155569.
   --- Fin de la trace de la pile d'exception interne ---
   à System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   à System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   à System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   à System.Reflection.Assembly.LoadFrom(String assemblyFile)
   à VRCFaceTracking.UnifiedLibManager.LoadExternalModules()
   à VRCFaceTracking.UnifiedLibManager.FindAndInitRuntimes(Boolean eye, Boolean lip)
   à VRCFaceTracking.UnifiedLibManager.<>c__DisplayClass7_0.<Initialize>b__0()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()

**Comment by dfgHiatus** [comment]
Try opening the file properties and clicking 'Unblock', like in this post: https://stackoverflow.com/questions/15238714/net-local-assembly-load-failed-with-cas-policy

**Comment by molresa** [comment]
Now It's working yay ! Thanks :D

**Comment by dfgHiatus** [comment]
Fantastic! Glad to help out
